import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import { neuemachina, pixel } from "./font";
import "./globals.css";
import "./style.css";
const jet = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--jet",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pixel.variable} ${neuemachina.variable} ${jet.variable} font-jet`}
      >
        {children}
      </body>
    </html>
  );
}
